### ISSUE TITLE
installation issue - please help

### ISSUE THREAD

**Issue by SaraJeanne08** [spodell/Darkhorse2#6]
upon installation I received the following error:

ERROR loading MySQL table nodes: contains 0 rows

this was after many lines of error messages similar to the following:

DBD::mysql::db do failed: Incorrect integer value: '' for column 'comments' at row 1 at /Users/Sara_Jeanne/Desktop/DarkHorse2/Darkhorse2-rev07/bin/installation_scripts/load_taxonomy_nodes.pl line 192, <INPUT> line 1662000.
  1663412 lines processed 
DBD::mysql::db do failed: Incorrect integer value: '' for column 'comments' at row 1 at /Users/Sara_Jeanne/Desktop/DarkHorse2/Darkhorse2-rev07/bin/installation_scripts/load_taxonomy_nodes.pl line 205, <INPUT> line 1663412.

thank you for your help with this.

Sara

**Comment by SaraJeanne08** [comment]
I made the adjustment to the script on line 116 like the other user but I am still getting the following error:

ERROR loading MySQL table nodes: contains 0 rows

**Comment by SaraJeanne08** [comment]
Can someone please help me? Is this program no longer supported?

**Comment by spodell** [comment]
Sorry for my delinquency in monitoring this site. Apparently NCBI has changed the format of their nodes table so the comments field is now in a different format than in versions from previous years. Thanks to user cparsania for posting the fix. In order to re-run the modified code on a previously created DarkHorse database, you'll probably need to drop the bad old nodes table first, using the mysql command line. I'll post a more permanent solution as soon as I have a chance to test it, preferably enabling backwards compatibility with older versions of NCBI databases.

 - Sheila

**Comment by spodell** [comment]
Fixed in latest release (DarkHorse-2.0_rev08).
