### ISSUE TITLE
Errors when I installed Darkhorse2

### ISSUE THREAD

**Issue by wangzhennan14** [spodell/Darkhorse2#8]
Hi,
    When I install the Darkhorse2 fellow the instruction, there was an error as follows:
     DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from nodes where tax_id=6' at line 1 at /home/bioSoft/Darkhorse2-DarkHorse-2.0_rev08/bin/installation_scripts/recursive_taxonomy_taxid.pl line 223, <INPUT> line 3.
Undefined subroutine &main::dieStackTrace called at /home/bioSoft/Darkhorse2-DarkHorse-2.0_rev08/bin/installation_scripts/recursive_taxonomy_taxid.pl line 223, <INPUT> line 3.
ERROR: Creation of file /home/bioSoft/Darkhorse2-DarkHorse-2.0_rev08/input_data/catalog_tax_id_lineages unsuccessful
      The version of mysql I used is 8.0.11. How can I solve this problem? Thank you very much!
                                                                                                                    Wang

**Comment by wangzhennan14** [comment]
Hi,
    Can you help me?  I need it! Thank you!

**Comment by spodell** [comment]
Problem is specific to Oracle (community) versions of MySQL, as routinely installed on OSX (doesn't happen in linux/MariaDB flavor of MySQL). Problem was Oracle-specific use of the word "rank" as a reserved keyword. Fixed in latest revision of recursive_taxonomy_taxid.pl - I will make a release 9 soon. Sorry this took so long.
